//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with data reading!.
        /// </summary>
        public static string ErrorDataReading {
            get {
                return ResourceManager.GetString("ErrorDataReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with data writing!.
        /// </summary>
        public static string ErrorDataWriting {
            get {
                return ResourceManager.GetString("ErrorDataWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: Duplicate Record!.
        /// </summary>
        public static string ErrorDuplicateRecord {
            get {
                return ResourceManager.GetString("ErrorDuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No course selected!.
        /// </summary>
        public static string ErrorNoCourseSelected {
            get {
                return ResourceManager.GetString("ErrorNoCourseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No professor selected!.
        /// </summary>
        public static string ErrorNoProfessorSelected {
            get {
                return ResourceManager.GetString("ErrorNoProfessorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record selected!.
        /// </summary>
        public static string ErrorNoRecordSelected {
            get {
                return ResourceManager.GetString("ErrorNoRecordSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No student selected!.
        /// </summary>
        public static string ErrorNoStudentSelected {
            get {
                return ResourceManager.GetString("ErrorNoStudentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This professor cannot teach this course!.
        /// </summary>
        public static string ErrorProfessorCannotTeachCourse {
            get {
                return ResourceManager.GetString("ErrorProfessorCannotTeachCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This professor already teaches four courses for the given day!.
        /// </summary>
        public static string ErrorProfessorMaxFourCoursesPerDay {
            get {
                return ResourceManager.GetString("ErrorProfessorMaxFourCoursesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This professor already teaches fourty courses for this week!.
        /// </summary>
        public static string ErrorProfessorMaxFourtyCoursesPerWeek {
            get {
                return ResourceManager.GetString("ErrorProfessorMaxFourtyCoursesPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This professor already teaches a subject for the given hour!.
        /// </summary>
        public static string ErrorProfessorTeachesDifferentSubjectGivenHour {
            get {
                return ResourceManager.GetString("ErrorProfessorTeachesDifferentSubjectGivenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: Same Professor and Student for this hour is given!.
        /// </summary>
        public static string ErrorSameStudentAndProfessor {
            get {
                return ResourceManager.GetString("ErrorSameStudentAndProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This student cannot learn this course!.
        /// </summary>
        public static string ErrorStudentCannotLearnCourse {
            get {
                return ResourceManager.GetString("ErrorStudentCannotLearnCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This student already attains a subject for the given hour!.
        /// </summary>
        public static string ErrorStudentLearnsDifferentSubjectGivenHour {
            get {
                return ResourceManager.GetString("ErrorStudentLearnsDifferentSubjectGivenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Entry: This student already attains three courses for the given day!.
        /// </summary>
        public static string ErrorStudentMaxThreeCoursesPerDay {
            get {
                return ResourceManager.GetString("ErrorStudentMaxThreeCoursesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Picture {
            get {
                object obj = ResourceManager.GetObject("Picture", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule updated successfully!.
        /// </summary>
        public static string ScheduleUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ScheduleUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Schedule Data to Load!.
        /// </summary>
        public static string WarningNoScheduleDataToLoad {
            get {
                return ResourceManager.GetString("WarningNoScheduleDataToLoad", resourceCulture);
            }
        }
    }
}
